add techleads to codeowners
forummlcb/topdup pull request #15
Opened 2021-01-09 01:28 UTC by forummlcb

2021-01-10 00:24 UTC, phamcong requested changes
/modules/web_app @phamcong

2021-01-12 16:55 UTC, forummlcb commented on CODEOWNERS
> +@tiepvupsu @tnlong1997 @hailoc12
```suggestion
@tiepvupsu @tnlong1997 @hailoc12 @seanphan
```

2021-01-12 16:55 UTC, forummlcb commented on CODEOWNERS
> +/modules/web_app/
```suggestion
/modules/web_app/ @phamcong
```

2021-01-12 16:56 UTC, forummlcb commented
> /modules/web_app @phamcong

done

2021-01-12 16:58 UTC, merged