Webapp
forummlcb/topdup pull request #52
Opened 2021-01-30 18:11 UTC by anhhd2703

1. đăng ký bằng email - gửi xác thực đến email - tạo callback
2. đăng nhập bằng email 
2. đăng nhập bằng fb
3. đăng nhập bằng google
4. đăng xuất. (tạm thời chỉ để client xóa token server không làm gì)
Do chưa rõ cấu trúc của db nên các tính năng trên chỉ xây dựng trên base và sẽ sửa khi cập nhật cấu trúc của database.
Xác thực khi user confirm chưa có vì chưa có cấu trúc db.

2021-01-30 19:52 UTC, phamcong requested changes

2021-01-30 19:52 UTC, phamcong commented on modules/web_app/backend/src/configs/index.js
> +export const GgUrl = 'https://www.googleapis.com/oauth2/v3'
```
export const externalAuthUrl = {
  fb: ''https://graph.facebook.com/v7.0',
  gg: 'https://www.googleapis.com/oauth2/v3'
}
```

2021-01-30 19:52 UTC, phamcong commented on modules/web_app/backend/src/controllers/auth.js
> +        let queryisExist = `
queryIsExist

2021-01-30 19:52 UTC, phamcong commented on modules/web_app/backend/src/controllers/auth.js
> +            const queryNewUser = `
queryAddUser

2021-01-30 19:52 UTC, phamcong commented on modules/web_app/backend/src/controllers/auth.js
> +const loginFaceBook = async (req, res) => {
loginByFacebook

2021-01-30 19:52 UTC, phamcong commented on modules/web_app/backend/src/controllers/auth.js
> +const loginGoogle = async (req, res) => {
loginByGoogle

2021-01-31 18:56 UTC, anhhd2703 commented
e thấy có mấy trường trong db không hợp lý lắm em sửa lại có được không vậy anh

2021-02-01 18:06 UTC, merged